-- V1__initial_schema.sql
-- PostgreSQL

-- =========================
-- Security / Auth tables
-- =========================
CREATE TABLE roles (
                       id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                       name VARCHAR(255) NOT NULL,
                       CONSTRAINT pk_roles      PRIMARY KEY (id),
                       CONSTRAINT uk_roles_name UNIQUE (name)
);

CREATE INDEX idx_roles_name ON roles (name);

CREATE TABLE capabilities (
                              id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                              name        VARCHAR(255) NOT NULL,
                              description VARCHAR(255) NULL,
                              CONSTRAINT pk_capabilities      PRIMARY KEY (id),
                              CONSTRAINT uk_capabilities_name UNIQUE (name)
);

CREATE INDEX idx_capabilities_name ON capabilities (name);

CREATE TABLE roles_capabilities (
                                    role_id       BIGINT NOT NULL,
                                    capability_id BIGINT NOT NULL,
                                    CONSTRAINT pk_roles_capabilities PRIMARY KEY (role_id, capability_id),
                                    CONSTRAINT fk_roles_capabilities_role
                                        FOREIGN KEY (role_id) REFERENCES roles (id)
                                            ON DELETE CASCADE,
                                    CONSTRAINT fk_roles_capabilities_capability
                                        FOREIGN KEY (capability_id) REFERENCES capabilities (id)
                                            ON DELETE CASCADE
);

CREATE INDEX idx_roles_capabilities_capability_id ON roles_capabilities (capability_id);

CREATE TABLE users (
                       id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                       uuid       UUID         NOT NULL,
                       username   VARCHAR(255) NOT NULL,
                       password   VARCHAR(255) NOT NULL,
                       role_id    BIGINT       NOT NULL,
                       created_at TIMESTAMPTZ  NOT NULL,
                       updated_at TIMESTAMPTZ  NOT NULL,
                       deleted    BOOLEAN      NOT NULL DEFAULT FALSE,
                       deleted_at TIMESTAMPTZ  NULL,
                       CONSTRAINT pk_users          PRIMARY KEY (id),
                       CONSTRAINT uk_users_uuid     UNIQUE (uuid),
                       CONSTRAINT uk_users_username UNIQUE (username),
                       CONSTRAINT fk_users_role
                           FOREIGN KEY (role_id) REFERENCES roles (id)
                               ON DELETE RESTRICT
);

CREATE INDEX ix_users_role_id    ON users (role_id);
CREATE INDEX ix_users_deleted    ON users (deleted);
CREATE INDEX ix_users_deleted_at ON users (deleted_at);

-- =========================
-- Network devices table
-- =========================

CREATE TABLE devices (
                         id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                         title        VARCHAR(150) NOT NULL,
                         manufacturer VARCHAR(100) NOT NULL,
                         model        VARCHAR(100) NOT NULL,
                         ip_address   VARCHAR(45) NOT NULL,
                         ssh_port     INT DEFAULT 22 NOT NULL,
                         username     VARCHAR(100) NOT NULL,
                         password     VARCHAR(255) NOT NULL,
                         created_at   TIMESTAMPTZ  NOT NULL,
                         updated_at   TIMESTAMPTZ  NOT NULL,
                         deleted      BOOLEAN DEFAULT FALSE NOT NULL,
                         deleted_at   TIMESTAMPTZ NULL,
                         CONSTRAINT   pk_devices PRIMARY KEY (id)
);

CREATE INDEX idx_active_network_devices ON devices(id) WHERE deleted = FALSE;